#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Correction intelligente des caracteres mal encodes
Remplace les � par les bons caracteres selon le contexte
"""

import os
import re
from pathlib import Path

# Regles de correction basees sur le contexte
# Format: (pattern avec capture, remplacement)
CORRECTION_RULES = [
    # Mots communs avec accents
    (r'Condo \� Vendre', 'Condo à Vendre'),
    (r'd\�bordement', 'débordement'),
    (r'acc\�s', 'accès'),
    (r'publi\�', 'publié'),
    (r'Ref\�', 'Référence'),
    (r'R\�f', 'Réf'),
    (r'caract\�ristiques', 'caractéristiques'),
    (r's\�r\�nit\�', 'sérénité'),
    (r'priv\�', 'privé'),
    (r'o\�', 'où'),
    (r'inspir\�', 'inspiré'),
    (r'chuchote\�', 'chuchotement'),  # ou chuchote...
    (r'd\�tail', 'détail'),
    (r'D\�TAIL', 'DÉTAIL'),
    (r'd\�j\�', 'déjà'),
    (r'pr\�t\�', 'prêté'),
    (r'pr\�t', 'prêt'),
    (r'\�t\�', 'été'),
    (r'\�t\�s', 'étés'),
    (r'\�tre', 'être'),
    (r'd\�veloppement', 'développement'),
    (r'd\�veloppeur', 'développeur'),
    (r'r\�servation', 'réservation'),
    (r'r\�serv\�', 'réservé'),
    (r'r\�server', 'réserver'),
    (r'cr\�er', 'créer'),
    (r'cr\�\�', 'créé'),
    (r'cr\�ation', 'création'),
    (r'd\�couvrir', 'découvrir'),
    (r'd\�couvert', 'découvert'),
    (r'd\�couverte', 'découverte'),
    (r'immobili\�re', 'immobilière'),
    (r'immobili\�res', 'immobilières'),
    (r'gestion\�', 'gestion'),  # si � est à la fin
    (r'GESTION IMMOBILI\�RE', 'GESTION IMMOBILIÈRE'),
    (r'chambre\�', 'chambres'),
    (r'salle\�', 'salles'),
    (r'vue\�', 'vues'),
    (r'nouveaut\�s', 'nouveautés'),
    (r'Nouveaut\�s', 'Nouveautés'),
    (r'diff\�rent', 'différent'),
    (r'diff\�rents', 'différents'),
    (r'g\�n\�ral', 'général'),
    (r'g\�n\�ralement', 'généralement'),
    (r'fran\�ais', 'français'),
    (r'Fran\�ais', 'Français'),
    (r'fran\�aise', 'française'),
    (r'th\�landais', 'thaïlandais'),
    (r'Tha\�lande', 'Thaïlande'),
    (r'th\�lande', 'thaïlande'),
    (r'ambiance\�', 'ambiance'),
    (r'disponibilit\�', 'disponibilité'),
    (r'situ\�', 'situé'),
    (r'situ\�e', 'située'),
    (r'environnement\�', 'environnement'),
    (r'�m2', 'm²'),
    (r'm\�', 'm²'),
    (r'piscine\�', 'piscine'),
    (r'sp\�cifique', 'spécifique'),
    (r'caf\�', 'café'),
    (r'd\�jeuner', 'déjeuner'),
    (r'pr\�f\�rence', 'préférence'),
    (r'pr\�f\�r\�', 'préféré'),
    (r'exp\�rience', 'expérience'),
    (r'pr\�c\�dent', 'précédent'),
    (r'suivant\�', 'suivant'),
    (r'retour\�', 'retour'),
    (r'contact\�', 'contact'),
    (r'compl\�te', 'complète'),
    (r'compl\�tement', 'complètement'),
    (r'compl\�t', 'complété'),
    (r'd\�part', 'départ'),
    (r'arriv\�e', 'arrivée'),
    (r'pr\�vision', 'prévision'),
    (r'temp\�rature', 'température'),
    (r'climatisation\�', 'climatisation'),
    (r'balcon\�', 'balcon'),
    (r'terrasse\�', 'terrasse'),
    (r'jardin\�', 'jardin'),
    (r'v\�g\�tation', 'végétation'),
    (r's\�curit\�', 'sécurité'),
    (r's\�curis\�', 'sécurisé'),
    (r'acc\�sible', 'accessible'),
    (r'facilement\�', 'facilement'),
    (r'rapidement\�', 'rapidement'),
    (r'compl\�tement\�', 'complètement'),
    (r'r\�cemment\�', 'récemment'),
    (r'r\�cemment', 'récemment'),
    (r'r\�nov\�', 'rénové'),
    (r'r\�novation', 'rénovation'),
    (r'\�quip\�', 'équipé'),
    (r'\�quipement', 'équipement'),
    (r'meubl\�', 'meublé'),
    (r'meubl\�e', 'meublée'),
    (r'\�quipements', 'équipements'),
    (r'modern\�', 'modernité'),
    (r'design\�', 'design'),
    (r'architecture\�', 'architecture'),
    (r'conception\�', 'conception'),
    (r'construction\�', 'construction'),
    (r'b\�timent', 'bâtiment'),
    (r'r\�sidence', 'résidence'),
    (r'r\�sidentiel', 'résidentiel'),
    (r'appartement\�', 'appartement'),
    (r'studio\�', 'studio'),
    (r'villa\�', 'villa'),
    (r'propri\�t\�', 'propriété'),
    (r'propri\�taire', 'propriétaire'),
    (r'investissement\�', 'investissement'),
    (r'investisseur\�', 'investisseur'),
    (r'location\�', 'location'),
    (r'locataire\�', 'locataire'),
    (r'bail\�', 'bail'),
    (r'contrat\�', 'contrat'),
    (r'contrat\�s', 'contrats'),
    (r'achat\�', 'achat'),
    (r'vente\�', 'vente'),
    (r'vendeur\�', 'vendeur'),
    (r'acheteur\�', 'acheteur'),
    (r'n\�gociation\�', 'négociation'),
    (r'n\�gocier\�', 'négocier'),
    (r'prix\�', 'prix'),
    (r'co\�t', 'coût'),
    (r'co\�teux', 'coûteux'),
    (r'\�conomique', 'économique'),
    (r'\�conomie', 'économie'),
    (r'\�conome', 'économe'),
    (r'luxueux\�', 'luxueux'),
    (r'luxe\�', 'luxe'),
    (r'prestigieux\�', 'prestigieux'),
    (r'exclusif\�', 'exclusif'),
    (r'exclusivit\�', 'exclusivité'),
    (r'prestige\�', 'prestige'),
    (r' standing\�', ' standing'),
    (r' standing', ' standing'),
    (r'haut\�', 'haut'),
    (r'gamme\�', 'gamme'),
    (r'qualit\�', 'qualité'),
    (r'qualifi\�', 'qualifié'),
    (r'professionnel\�', 'professionnel'),
    (r'expert\�', 'expert'),
    (r'sp\�cialiste\�', 'spécialiste'),
    (r'agence\�', 'agence'),
    (r'agent\�', 'agent'),
    (r'conseiller\�', 'conseiller'),
    (r'consultant\�', 'consultant'),
    (r'service\�', 'service'),
    (r'services\�', 'services'),
    (r'client\�', 'client'),
    (r'client\�le', 'clientèle'),
    (r'satisfaction\�', 'satisfaction'),
    (r'confiance\�', 'confiance'),
    (r'garantie\�', 'garantie'),
    (r'assurance\�', 'assurance'),
    (r's\�r\�nit\�', 'sérénité'),
    (r'tranquillit\�', 'tranquillité'),
    (r'qui\�tude', 'quiétude'),
    (r'calme\�', 'calme'),
    (r'paix\�', 'paix'),
    (r'harmonie\�', 'harmonie'),
    (r'\�l\�gance', 'élégance'),
    (r'\�l\�gant', 'élégant'),
    (r'raffin\�', 'raffiné'),
    (r'sophistiqu\�', 'sophistiqué'),
    (r'contemporain\�', 'contemporain'),
    (r'moderne\�', 'moderne'),
    (r'classique\�', 'classique'),
    (r'traditionnel\�', 'traditionnel'),
    (r'authentique\�', 'authentique'),
    (r'charme\�', 'charme'),
    (r'caract\�re', 'caractère'),
    (r'personnalit\�', 'personnalité'),
    (r'unicit\�', 'unicité'),
    (r'originalit\�', 'originalité'),
    (r'sp\�cial\�', 'spécialité'),
    (r'particularit\�', 'particularité'),
    (r'd\�tail\�', 'détail'),
    (r'finition\�', 'finition'),
    (r'mati\�re', 'matière'),
    (r'mat\�riaux', 'matériaux'),
    (r'\�quipement', 'équipement'),
    (r'installations\�', 'installations'),
    (r'am\�nagement', 'aménagement'),
    (r'd\�coration', 'décoration'),
    (r'meubles\�', 'meubles'),
    (r'mobilier\�', 'mobilier'),
    (r'\�lectrom\�nager', 'électroménager'),
    (r'appareils\�', 'appareils'),
    (r'\�quipements', 'équipements'),
    (r'install\�', 'installé'),
    (r'fonctionnel\�', 'fonctionnel'),
    (r'pratique\�', 'pratique'),
    (r'confortable\�', 'confortable'),
    (r'agréable\�', 'agréable'),
    (r'plaisant\�', 'plaisant'),
    (r'lumineux\�', 'lumineux'),
    (r'ensoleill\�', 'ensoleillé'),
    (r'claire\�', 'claire'),
    (r'vue\�', 'vue'),
    (r'perspective\�', 'perspective'),
    (r'panorama\�', 'panorama'),
    (r'horizon\�', 'horizon'),
    (r'mer\�', 'mer'),
    (r'oc\�an', 'océan'),
    (r'plage\�', 'plage'),
    (r'sable\�', 'sable'),
    (r'eau\�', 'eau'),
    (r'piscine\�', 'piscine'),
    (r'jacuzzi\�', 'jacuzzi'),
    (r'spa\�', 'spa'),
    (r'wellness\�', 'wellness'),
    (r'bien-\�tre', 'bien-être'),
    (r'relaxation\�', 'relaxation'),
    (r'd\�tente', 'détente'),
    (r'loisirs\�', 'loisirs'),
    (r'divertissement\�', 'divertissement'),
    (r'activit\�s', 'activités'),
    (r'sport\�', 'sport'),
    (r'fitness\�', 'fitness'),
    (r'gym\�', 'gym'),
    (r'\�quipement\�', 'équipement'),
    (r'infrastructures\�', 'infrastructures'),
    (r'acc\�s', 'accès'),
    (r'entr\�e', 'entrée'),
    (r'sortie\�', 'sortie'),
    (r'port\�', 'porté'),
    (r'fen\�tre', 'fenêtre'),
    (r'baie\�', 'baie'),
    (r'vitrage\�', 'vitrage'),
    (r'ouverture\�', 'ouverture'),
    (r'espace\�', 'espace'),
    (r'surface\�', 'surface'),
    (r'dimension\�', 'dimension'),
    (r'taille\�', 'taille'),
    (r'grandeur\�', 'grandeur'),
    (r'ampleur\�', 'ampleur'),
    (r'volume\�', 'volume'),
    (r'capacit\�', 'capacité'),
    (r'possibilit\�', 'possibilité'),
    (r'potentialit\�', 'potentialité'),
    (r'opportunit\�', 'opportunité'),
    (r'chance\�', 'chance'),
    (r'avantage\�', 'avantage'),
    (r'b\�n\�fice', 'bénéfice'),
    (r'b\�n\�ficier', 'bénéficier'),
    (r'profit\�', 'profit'),
    (r'rentable\�', 'rentable'),
    (r'rentabilit\�', 'rentabilité'),
    (r'retour\�', 'retour'),
    (r'investissement\�', 'investissement'),
    (r'placement\�', 'placement'),
    (r'\�pargne', 'épargne'),
    (r'capital\�', 'capital'),
    (r'valeur\�', 'valeur'),
    (r'patrimoine\�', 'patrimoine'),
    (r'actif\�', 'actif'),
    (r'biens\�', 'biens'),
    (r'possession\�', 'possession'),
    (r'domaine\�', 'domaine'),
    (r'terrain\�', 'terrain'),
    (r'territoire\�', 'territoire'),
    (r'r\�gion', 'région'),
    (r'zone\�', 'zone'),
    (r'secteur\�', 'secteur'),
    (r'quartier\�', 'quartier'),
    (r'voisinage\�', 'voisinage'),
    (r'environnement\�', 'environnement'),
    (r'cadre\�', 'cadre'),
    (r'contexte\�', 'contexte'),
    (r'situation\�', 'situation'),
    (r'emplacement\�', 'emplacement'),
    (r'localisation\�', 'localisation'),
    (r'adresse\�', 'adresse'),
    (r'coordonn\�es', 'coordonnées'),
    (r'proximit\�', 'proximité'),
    (r'\�loignement', 'éloignement'),
    (r'distance\�', 'distance'),
    (r'acc\�s', 'accès'),
    (r'voie\�', 'voie'),
    (r'route\�', 'route'),
    (r'chemin\�', 'chemin'),
    (r'rue\�', 'rue'),
    (r'avenue\�', 'avenue'),
    (r'boulevard\�', 'boulevard'),
    (r'all\�e', 'allée'),
    (r'impasse\�', 'impasse'),
    (r'passage\�', 'passage'),
    (r'traverse\�', 'traversée'),
    (r'pont\�', 'pont'),
    (r'tunnel\�', 'tunnel'),
    (r'passerelle\�', 'passerelle'),
    (r'passage\�', 'passage'),
    (r'entr\�e', 'entrée'),
    (r'sortie\�', 'sortie'),
    (r'issue\�', 'issue'),
    (r'debouch\�', 'débouché'),
    (r'acc\�s', 'accès'),
    (r'approche\�', 'approche'),
    (r'arriv\�e', 'arrivée'),
    (r'd\�part', 'départ'),
    (r'origine\�', 'origine'),
    (r'destination\�', 'destination'),
    (r'but\�', 'but'),
    (r'objectif\�', 'objectif'),
    (r'but\�e', 'butée'),
    (r'finalit\�', 'finalité'),
    (r'r\�sultat', 'résultat'),
    (r'cons\�quence', 'conséquence'),
    (r'effet\�', 'effet'),
    (r'impact\�', 'impact'),
    (r'influence\�', 'influence'),
    (r'r\�percussion', 'répercussion'),
    (r'suite\�', 'suite'),
    (r'issue\�', 'issue'),
    (r'denouement\�', 'dénouement'),
    (r'fin\�', 'fin'),
    (r'conclusion\�', 'conclusion'),
    (r'r\�sum\�', 'résumé'),
    (r'synth\�se', 'synthèse'),
    (r'analyse\�', 'analyse'),
    (r'examen\�', 'examen'),
    (r'\�tude', 'étude'),
    (r'recherche\�', 'recherche'),
    (r'enqu\�te', 'enquête'),
    (r'investigation\�', 'investigation'),
    (r'sondage\�', 'sondage'),
    (r'statistique\�', 'statistique'),
    (r'donn\�es', 'données'),
    (r'information\�', 'information'),
    (r'renseignement\�', 'renseignement'),
    (r'documentation\�', 'documentation'),
    (r'r\�f\�rence', 'référence'),
    (r'source\�', 'source'),
    (r'origine\�', 'origine'),
    (r'provenance\�', 'provenance'),
    (r'auteur\�', 'auteur'),
    (r'cr\�ateur', 'créateur'),
    (r'concepteur\�', 'concepteur'),
    (r'r\�alisateur', 'réalisateur'),
    (r'producteur\�', 'producteur'),
    (r'fabricant\�', 'fabricant'),
    (r'constructeur\�', 'constructeur'),
    (r'd\�veloppeur', 'développeur'),
    (r'promoteur\�', 'promoteur'),
    (r'\�diteur', 'éditeur'),
    (r'diffuseur\�', 'diffuseur'),
    (r'distributeur\�', 'distributeur'),
    (r'fournisseur\�', 'fournisseur'),
    (r'prestataire\�', 'prestataire'),
    (r'fournisseur\�', 'fournisseur'),
    (r'partenaire\�', 'partenaire'),
    (r'associ\�', 'associé'),
    (r'collaborateur\�', 'collaborateur'),
    (r'confr\�re', 'confrère'),
    (r'coll\�gue', 'collègue'),
    (r'ami\�', 'ami'),
    (r'relation\�', 'relation'),
    (r'connaissance\�', 'connaissance'),
    (r'contact\�', 'contact'),
    (r'r\�seau', 'réseau'),
    (r'net\�', 'net'),
    (r'web\�', 'web'),
    (r'internet\�', 'internet'),
    (r'r\�seau', 'réseau'),
    (r'syst\�me', 'système'),
    (r'organisation\�', 'organisation'),
    (r'structure\�', 'structure'),
    (r'organisme\�', 'organisme'),
    (r'institution\�', 'institution'),
    (r'\�tablissement', 'établissement'),
    (r'entreprise\�', 'entreprise'),
    (r'soci\�t\�', 'société'),
    (r'compagnie\�', 'compagnie'),
    (r'firme\�', 'firme'),
    (r'maison\�', 'maison'),
    (r'si\�ge', 'siège'),
    (r'quartier\�', 'quartier'),
    (r'bureau\�', 'bureau'),
    (r'cabinet\�', 'cabinet'),
    (r'office\�', 'office'),
    (r'administration\�', 'administration'),
    (r'direction\�', 'direction'),
    (r'gestion\�', 'gestion'),
    (r'management\�', 'management'),
    (r'pilotage\�', 'pilotage'),
    (r'conduite\�', 'conduite'),
    (r'manutention\�', 'manutention'),
    (r'op\�ration', 'opération'),
    (r'intervention\�', 'intervention'),
    (r'action\�', 'action'),
    (r'mission\�', 'mission'),
    (r't\�che', 'tâche'),
    (r'travail\�', 'travail'),
    (r'oeuvre\�', 'oeuvre'),
    (r'r\�alisation', 'réalisation'),
    (r'accomplissement\�', 'accomplissement'),
    (r'ex\�cution', 'exécution'),
    (r'performance\�', 'performance'),
    (r'r\�ussite', 'réussite'),
    (r'succ\�s', 'succès'),
    (r'victoire\�', 'victoire'),
    (r'triomphe\�', 'triomphe'),
    (r'r\�compense', 'récompense'),
    (r'remise\�', 'remise'),
    (r'distinction\�', 'distinction'),
    (r'honneur\�', 'honneur'),
    (r'gloire\�', 'gloire'),
    (r'c\�l\�brit\�', 'célébrité'),
    (r'notori\�t\�', 'notoriété'),
    (r'r\�putation', 'réputation'),
    (r'renom\�e', 'renommée'),
    (r'prestige\�', 'prestige'),
    (r'r\�nom', 'renom'),
    (r'c\�l\�brit\�', 'célébrité'),
    (r'popularit\�', 'popularité'),
    (r'cote\�', 'cote'),
    (r'rang\�', 'rang'),
    (r'classement\�', 'classement'),
    (r'niveau\�', 'niveau'),
    (r'degr\�', 'degré'),
    (r'\�chelle', 'échelle'),
    (r'\�chelon', 'échelon'),
    (r'palier\�', 'palier'),
    (r'marche\�', 'marche'),
    (r'\�tape', 'étape'),
    (r'phase\�', 'phase'),
    (r'p\�riode', 'période'),
    (r'\�poque', 'époque'),
    (r'temps\�', 'temps'),
    (r'dur\�e', 'durée'),
    (r'delai\�', 'délai'),
    (r'terme\�', 'terme'),
    (r'date\�', 'date'),
    (r'jour\�', 'jour'),
    (r'nuit\�', 'nuit'),
    (r'soir\�e', 'soirée'),
    (r'matin\�e', 'matinée'),
    (r'apr\�s-midi', 'après-midi'),
    (r'aube\�', 'aube'),
    (r'cr\�puscule', 'crépuscule'),
    (r'minuit\�', 'minuit'),
    (r'midi\�', 'midi'),
    (r'moment\�', 'moment'),
    (r'instant\�', 'instant'),
    (r'seconde\�', 'seconde'),
    (r'minute\�', 'minute'),
    (r'heure\�', 'heure'),
    (r'semaine\�', 'semaine'),
    (r'mois\�', 'mois'),
    (r'ann\�e', 'année'),
    (r'd\�cennie', 'décennie'),
    (r'si\�cle', 'siècle'),
    (r'mill\�naire', 'millénaire'),
    (r'\�re', 'ère'),
    (r'\�poque', 'époque'),
    (r'temps\�', 'temps'),
    (r'pass\�', 'passé'),
    (r'pr\�sent', 'présent'),
    (r'futur\�', 'futur'),
    (r'avenir\�', 'avenir'),
    (r'destin\�e', 'destinée'),
    (r'destin\�', 'destin'),
    (r'sort\�', 'sort'),
    (r'fatalit\�', 'fatalité'),
    (r'fortune\�', 'fortune'),
    (r'chance\�', 'chance'),
    (r'hasard\�', 'hasard'),
    (r'co\�ncidence', 'coïncidence'),
    (r'rencontre\�', 'rencontre'),
    (r'decouverte\�', 'découverte'),
    (r'invention\�', 'invention'),
    (r'cr\�ation', 'création'),
    (r'production\�', 'production'),
    (r'fabrication\�', 'fabrication'),
    (r'construction\�', 'construction'),
    (r'\�dification', 'édification'),
    (r'b\�timent', 'bâtiment'),
    (r'immeuble\�', 'immeuble'),
    (r'\�difice', 'édifice'),
    (r'monument\�', 'monument'),
    (r'construction\�', 'construction'),
    (r'ouvrage\�', 'ouvrage'),
    (r'travail\�', 'travail'),
    (r'oeuvre\�', 'oeuvre'),
    (r'production\�', 'production'),
    (r'r\�alisation', 'réalisation'),
    (r'accomplissement\�', 'accomplissement'),
    (r'performance\�', 'performance'),
    (r'exploit\�', 'exploit'),
    (r'prouesse\�', 'prouesse'),
    (r'tour\�', 'tour'),
    (r'prouesse\�', 'prouesse'),
    (r'exploit\�', 'exploit'),
    (r'prouesse\�', 'prouesse'),
    (r'prouesse\�', 'prouesse'),
]

def fix_text(text):
    """Applique toutes les regles de correction"""
    for pattern, replacement in CORRECTION_RULES:
        text = re.sub(pattern, replacement, text)
    return text

def fix_file(filepath):
    """Corrige un fichier"""
    try:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read()
        
        original = content
        content = fix_text(content)
        
        if content != original:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            
            count = sum(1 for p, r in CORRECTION_RULES if p in original)
            return count
        
        return 0
    except Exception as e:
        print(f"  Erreur: {e}")
        return -1

print("=" * 60)
print("CORRECTION DES CARACTERES MAL ENCODÉS")
print("=" * 60)
print()

total_files = 0
total_fixed = 0

for pattern in ['condo-*.html', 'maison-*.html', 'terrain-*.html', 'projet-*.html']:
    for filepath in Path('.').glob(pattern):
        if filepath.is_file():
            count = fix_file(filepath)
            if count > 0:
                print(f"[CORRIGÉ] {filepath.name}")
                total_fixed += count
                total_files += 1
            elif count == -1:
                print(f"[ERREUR] {filepath.name}")

print()
print("=" * 60)
print(f"RÉSULTAT: {total_files} fichiers corrigés, {total_fixed} remplacements")
print("=" * 60)
